name: "OpenAPI Diff Action"
description: "Find breaking and non-breaking changes in OpenAPI specs"

branding:
  icon: copy
  color: green

inputs:
  github_token:
    description: "A personal access token to use; this token is used to add comments and labels to pull requests"
    required: true
  base_spec:
    description: "The relative path or http url of the BASE (old) spec"
    required: true
  head_spec:
    description: "The relative path or http url of the HEAD (new) spec"
    required: true
  add_comment:
    description: "Set to true if comment should be added, not overwritten"
    required: false
    default: True

outputs:
  classification:
    description: "The type of change detected; possible values: 'major', 'minor', 'patch'"

runs:
  using: docker
  image: Dockerfile
