name: "OpenAPI Diff Action"
description: "Find breaking and non-breaking changes in OpenAPI specs"

branding:
  icon: copy
  color: green

inputs:
  github-token:
    description: "A personal access token to use; this token is used to add comments and labels to pull requests"
    required: true
  base-spec:
    description: "The relative path or http url of the BASE (old) spec"
    required: true
  head-spec:
    description: "The relative path or http url of the HEAD (new) spec"
    required: true
  add-comment:
    description: "Set to true if comment should be added, not overwritten"
    required: false

outputs:
  classification:
    description: "The type of change detected; possible values: 'major', 'minor', 'patch'"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.github-token, github.event.pull_request.number, inputs.base-spec, inputs.head-spec, inputs.add-comment}}
