name: "OpenAPI Diff in PR"
description: "Automatically compare OpenAPI v3 specification files and post result in PR"

branding:
  icon: file-text
  color: blue

inputs:
  github_token:
    description: "A personal access token to use; this token is used to add comments and labels to pull requests"
    required: true
  base_spec:
    description: "The relative path or http url of the BASE (old) spec"
    required: true
  head_spec:
    description: "The relative path or http url of the HEAD (new) spec"
    required: true
  output_path:
    description: "The local path to store the output file"
    required: true
  add_comment:
    description: "Set to true if comment should be added, not overwritten"
    required: false
    default: "false"
  exclude_labels:
    description: "Set to true if no labels should be added"
    required: false
    default: "false"

outputs:
  classification:
    description: "The type of change detected; possible values: 'major', 'minor', 'patch'"

runs:
  using: docker
  image: Dockerfile
